services:
  ros1:
    build:
      context: .
      dockerfile: ros1.Dockerfile
    command: roslaunch roscpp_tutorials talker_listener.launch

  ros2:
    build:
      context: .
      dockerfile: ros2.Dockerfile
    command: ros2 run demo_nodes_cpp talker

  bridge:
    image: ros:foxy-ros1-bridge
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://ros1:11311"
    command: ros2 run ros1_bridge dynamic_bridge

  ubuntu20:
    build:
      context: .
      dockerfile: ubuntu20.Dockerfile
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./ws_ros2:/ws_ros2
      # convenience: make bash history persistent
      - ubuntu20_bash_history:/root/.bash_history

  rust:
    build:
      context: .
      dockerfile: rust.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./ws_rust:/workspace/src/ros2_rust/
      - build_artifacts:/workspace/build/
      - install_artifacts:/workspace/install/
      - log_artifacts:/workspace/log/
      # to avoid time skew in saved logs, make sure container time is in sync with host
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # convenience: make bash history persistent
      - rust_bash_history:/root/.bash_history


# named volumes to store build artifacts to avoid re-compilation when recreating the container
volumes:
  build_artifacts:
  install_artifacts:
  log_artifacts:
  rust_bash_history:
  ubuntu20_bash_history: